apiVersion: v1
entries:
  emqx:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-09-27T15:08:51.756548744-04:00"
    description: A Helm chart for EMQX
    digest: 90f7870edea000aff8c2940560191a4a33a3122bc89dc932d7981f04eb4650d2
    icon: https://github.com/emqx.png
    name: emqx
    type: application
    urls:
    - https://jardeelc.github.io/helm-charts/charts/emqx-1.0.0.tgz
    version: 1.0.0
generated: "2024-09-27T15:08:51.755561692-04:00"
